### ISSUE TITLE
Chat name color not working in 1.20

### ISSUE THREAD

**Issue by Rothorok** [kateowo/name-colours#1]
Hi, I reached out to you on planetminecraft.com, but I think you might notice a message on this website sooner. So, I'll copypaste my message:

I installed this on a 1.20 server, but I can't get it to properly work. It displays the color in the Tab screen and when a player enters or leaves the server and when a player gets an achievment, but it doesn't work when someone just talks in chat. Weird thing is, in singleplayyer it does work perfectly, but not on my server. I got no mods, no fabric, nothing like that. Any idea what could I do?

**Comment by katelmao** [comment]
was dealt with on planetminecraft iirc
